In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import models
import skimage
from skimage import io
import os
import glob
import numpy as np
from skimage import exposure, measure
from skimage.transform import rotate
import re
from torch.utils.data import Dataset

In [7]:
def dir_to_file_lists(directory):
    os.chdir(directory)
    input_list = []
    target_list = []
    all_tifs = glob.glob("*.tif")
    input_tifs = [file for file in all_tifs if '_channel2_' in file]
    input_tifs.sort()
    output_tifs = [file for file in all_tifs if '_channel6_' in file]
    output_tifs.sort()
    return(input_tifs, output_tifs)

In [8]:
input_tifs, output_tifs = dir_to_file_lists('/gpfs/data/lionnetlab/cellvision/pilotdata/20181009-top50')

In [9]:
def image_to_matrix_dataset(file_list):
    """
    funciton takes list of file names and returns list of matrices
    list will be 6 times as long since data is flipped + rotated too
    """
    
    mat_list = []
    for file in file_list:
        orig = io.imread(file)
        mat_list.append(orig)
        
        #vertical flip
        vert_flip = orig[::-1]
        mat_list.append(vert_flip)
        
        #horizonal flip
        horiz_flip = np.flip(orig,1)
        mat_list.append(horiz_flip)
        
        #rotate 90 degrees
        rot_90 = rotate(orig, 90)
        mat_list.append(rot_90)
        
        #rotate 180 degrees
        rot_180 = rotate(orig, 180)
        mat_list.append(rot_180)
        
        #rotate 270 degrees
        rot_270 = rotate(orig, 270)
        mat_list.append(rot_270)
    return(mat_list)

In [13]:
input_tifs_mats = image_to_matrix_dataset(input_tifs[:100])
output_tifs_mats = image_to_matrix_dataset(output_tifs[:100])
# write to pickle

# read from pickle

In [17]:
class two_image_dataset(Dataset):
    
    def __init__(self, input_tifs_mats, output_tifs_mats):
        
        self.input_tifs_mats = input_tifs_mats
        self.output_tifs_mats = output_tifs_mats
        assert (len(self.input_tifs_mats) == len(self.output_tifs_mats))
    
    def __len__(self):
        return len(self.input_tifs_mats)
    
    def __getitem__(self, key):
        """
        Triggered when you call dataset[i]
        """
        input_mat = self.input_tifs_mats[key]
        output_mat = self.output_tifs_mats[key]
        return [input_mat, output_mat]

In [18]:
def two_image_collate_func(batch):
    """
    function that returns input and target as tensors
    """
    input_list = []
    target_list = []
    for datum in batch:
        input_list.append(datum[0].astype(dtype = 'int32'))
        target_list.append(datum[1].astype(dtype = 'int32'))
    input_tensor = torch.from_numpy(np.array(input_list))
    target_tensor = torch.from_numpy(np.array(input_list))
    return [input_tensor, target_tensor]

In [21]:
BATCH_SIZE = 4
all_dataset = two_image_dataset(input_tifs_mats, output_tifs_mats)
all_loader = torch.utils.data.DataLoader(dataset=all_dataset, 
                                           batch_size=BATCH_SIZE,
                                           collate_fn=two_image_collate_func,
                                           shuffle=False)

In [ ]:
for i, (mat1, mat2) in enumerate(all_loader):
    print(i)
    print(mat1)
    print(mat2)

0
tensor([[[ 241,  215,  206,  ...,  286,  203,  211],
         [ 217,  224,  228,  ...,  223,  176,  204],
         [ 208,  219,  243,  ...,  245,  209,  208],
         ...,
         [1124, 1134, 1168,  ...,  345,  320,  350],
         [1027, 1054, 1084,  ...,  346,  345,  336],
         [1131, 1117, 1127,  ...,  317,  304,  381]],

        [[1131, 1117, 1127,  ...,  317,  304,  381],
         [1027, 1054, 1084,  ...,  346,  345,  336],
         [1124, 1134, 1168,  ...,  345,  320,  350],
         ...,
         [ 208,  219,  243,  ...,  245,  209,  208],
         [ 217,  224,  228,  ...,  223,  176,  204],
         [ 241,  215,  206,  ...,  286,  203,  211]],

        [[ 211,  203,  286,  ...,  206,  215,  241],
         [ 204,  176,  223,  ...,  228,  224,  217],
         [ 208,  209,  245,  ...,  243,  219,  208],
         ...,
         [ 350,  320,  345,  ..., 1168, 1134, 1124],
         [ 336,  345,  346,  ..., 1084, 1054, 1027],
         [ 381,  304,  317,  ..., 1127, 1117, 1131]

tensor([[[231, 213, 202,  ..., 275, 243, 298],
         [185, 273, 226,  ..., 235, 328, 262],
         [223, 252, 241,  ..., 277, 239, 220],
         ...,
         [424, 381, 358,  ..., 408, 426, 473],
         [351, 362, 417,  ..., 442, 485, 456],
         [397, 391, 426,  ..., 497, 441, 442]],

        [[397, 391, 426,  ..., 497, 441, 442],
         [351, 362, 417,  ..., 442, 485, 456],
         [424, 381, 358,  ..., 408, 426, 473],
         ...,
         [223, 252, 241,  ..., 277, 239, 220],
         [185, 273, 226,  ..., 235, 328, 262],
         [231, 213, 202,  ..., 275, 243, 298]],

        [[298, 243, 275,  ..., 202, 213, 231],
         [262, 328, 235,  ..., 226, 273, 185],
         [220, 239, 277,  ..., 241, 252, 223],
         ...,
         [473, 426, 408,  ..., 358, 381, 424],
         [456, 485, 442,  ..., 417, 362, 351],
         [442, 441, 497,  ..., 426, 391, 397]],

        [[  0,   0,   0,  ...,   0,   0,   0],
         [  0,   0,   0,  ...,   0,   0,   0],
         [  

tensor([[[   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         ...,
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0]],

        [[   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         ...,
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0]],

        [[ 256,  228,  266,  ...,  178,  243,  248],
         [ 225,  265,  249,  ...,  196,  230,  172],
         [ 224,  225,  235,  ...,  238,  217,  171],
         ...,
         [1025, 1065,  969,  ...,  334,  326,  295],
         [1024, 1017,  996,  ...,  305,  312,  283],
         [ 949,  949, 1053,  ...,  303,  272,  310]],

tensor([[[   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         ...,
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0]],

        [[   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         ...,
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0]],

        [[ 235,  229,  219,  ...,  239,  222,  223],
         [ 231,  198,  181,  ...,  157,  207,  242],
         [ 218,  234,  199,  ...,  213,  217,  232],
         ...,
         [ 896, 1030, 1067,  ...,  267,  242,  348],
         [ 872, 1065,  937,  ...,  283,  296,  313],
         [ 843,  998,  963,  ...,  297,  350,  278]],

tensor([[[ 245,  227,  240,  ...,  245,  235,  180],
         [ 240,  216,  222,  ...,  233,  221,  242],
         [ 228,  185,  191,  ...,  212,  217,  265],
         ...,
         [ 260,  312,  278,  ..., 1042,  905,  917],
         [ 284,  282,  324,  ...,  969,  961,  999],
         [ 285,  305,  249,  ...,  867,  965,  831]],

        [[   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         ...,
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0]],

        [[   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         ...,
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0]],

tensor([[[ 216,  231,  204,  ...,  256,  205,  203],
         [ 236,  212,  219,  ...,  225,  236,  216],
         [ 189,  257,  215,  ...,  219,  206,  201],
         ...,
         [ 281,  307,  295,  ..., 1006,  981,  836],
         [ 297,  335,  254,  ..., 1028,  828,  922],
         [ 258,  264,  300,  ..., 1016, 1072,  893]],

        [[   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         ...,
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0]],

        [[   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         ...,
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0]],

tensor([[[ 203,  224,  250,  ...,  234,  218,  233],
         [ 218,  200,  264,  ...,  180,  229,  208],
         [ 183,  177,  243,  ...,  214,  221,  198],
         ...,
         [ 812,  952,  862,  ...,  288,  300,  301],
         [ 912,  978, 1000,  ...,  304,  289,  328],
         [1011,  920,  902,  ...,  308,  305,  289]],

        [[1011,  920,  902,  ...,  308,  305,  289],
         [ 912,  978, 1000,  ...,  304,  289,  328],
         [ 812,  952,  862,  ...,  288,  300,  301],
         ...,
         [ 183,  177,  243,  ...,  214,  221,  198],
         [ 218,  200,  264,  ...,  180,  229,  208],
         [ 203,  224,  250,  ...,  234,  218,  233]],

        [[ 233,  218,  234,  ...,  250,  224,  203],
         [ 208,  229,  180,  ...,  264,  200,  218],
         [ 198,  221,  214,  ...,  243,  177,  183],
         ...,
         [ 301,  300,  288,  ...,  862,  952,  812],
         [ 328,  289,  304,  ..., 1000,  978,  912],
         [ 289,  305,  308,  ...,  902,  920, 1011]],

tensor([[[ 191,  209,  242,  ...,  221,  189,  222],
         [ 242,  196,  210,  ...,  225,  253,  207],
         [ 219,  228,  214,  ...,  238,  218,  181],
         ...,
         [ 907,  927,  841,  ...,  288,  304,  277],
         [ 868, 1054,  847,  ...,  288,  303,  312],
         [ 843,  908,  931,  ...,  303,  307,  276]],

        [[ 843,  908,  931,  ...,  303,  307,  276],
         [ 868, 1054,  847,  ...,  288,  303,  312],
         [ 907,  927,  841,  ...,  288,  304,  277],
         ...,
         [ 219,  228,  214,  ...,  238,  218,  181],
         [ 242,  196,  210,  ...,  225,  253,  207],
         [ 191,  209,  242,  ...,  221,  189,  222]],

        [[ 222,  189,  221,  ...,  242,  209,  191],
         [ 207,  253,  225,  ...,  210,  196,  242],
         [ 181,  218,  238,  ...,  214,  228,  219],
         ...,
         [ 277,  304,  288,  ...,  841,  927,  907],
         [ 312,  303,  288,  ...,  847, 1054,  868],
         [ 276,  307,  303,  ...,  931,  908,  843]],

tensor([[[   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         ...,
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0]],

        [[   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         ...,
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0],
         [   0,    0,    0,  ...,    0,    0,    0]],

        [[ 221,  226,  220,  ...,  222,  205,  208],
         [ 230,  197,  225,  ...,  230,  188,  190],
         [ 219,  229,  210,  ...,  202,  233,  192],
         ...,
         [ 822,  878,  857,  ...,  298,  280,  257],
         [ 789,  917,  987,  ...,  321,  275,  240],
         [ 801,  927,  982,  ...,  256,  310,  297]],

In [30]:
# UNET arch here
def convrelu(in_channels, out_channels, kernel, padding):
    return nn.Sequential(
        nn.Conv2d(in_channels, out_channels, kernel, padding=padding),
        nn.ReLU(inplace=True),
    )

class ResNetUNet(nn.Module):

    def __init__(self):
        super().__init__()

        # Use ResNet18 as the encoder with the pretrained weights
        base_model = models.resnet18(pretrained=True)
        self.base_layers = list(base_model.children())

        self.layer0 = nn.Sequential(*self.base_layers[:3]) # size=(N, 64, x.H/2, x.W/2)
        self.layer0_1x1 = convrelu(64, 64, 1, 0)
        self.layer1 = nn.Sequential(*self.base_layers[3:5]) # size=(N, 256, x.H/4, x.W/4)
        self.layer1_1x1 = convrelu(256, 256, 1, 0)
        self.layer2 = self.base_layers[5]  # size=(N, 512, x.H/8, x.W/8)
        self.layer2_1x1 = convrelu(512, 512, 1, 0)
        self.layer3 = self.base_layers[6]  # size=(N, 1024, x.H/16, x.W/16)
        self.layer3_1x1 = convrelu(1024, 512, 1, 0)
        self.layer4 = self.base_layers[7]  # size=(N, 2048, x.H/32, x.W/32)
        self.layer4_1x1 = convrelu(2048, 1024, 1, 0)

        self.upsample = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)

        self.conv_up3 = convrelu(512 + 1024, 512, 3, 1)
        self.conv_up2 = convrelu(512 + 512, 512, 3, 1)
        self.conv_up1 = convrelu(256 + 512, 256, 3, 1)
        self.conv_up0 = convrelu(64 + 256, 128, 3, 1)

        self.conv_original_size0 = convrelu(3, 64, 3, 1)
        self.conv_original_size1 = convrelu(64, 64, 3, 1)
        self.conv_original_size2 = convrelu(64 + 128, 64, 3, 1)

        self.conv_last = nn.Conv2d(64, 1, 1)

    def forward(self, input):
        x_original = self.conv_original_size0(input)
        x_original = self.conv_original_size1(x_original)

        layer0 = self.layer0(input)
        layer1 = self.layer1(layer0)
        layer2 = self.layer2(layer1)
        layer3 = self.layer3(layer2)
        layer4 = self.layer4(layer3)

        # Upsample the last/bottom layer
        layer4 = self.layer4_1x1(layer4)
        x = self.upsample(layer4)
        # Create the shortcut from the encoder
        layer3 = self.layer3_1x1(layer3)
        x = torch.cat([x, layer3], dim=1)
        x = self.conv_up3(x)

        x = self.upsample(x)
        layer2 = self.layer2_1x1(layer2)
        x = torch.cat([x, layer2], dim=1)
        x = self.conv_up2(x)

        x = self.upsample(x)
        layer1 = self.layer1_1x1(layer1)
        x = torch.cat([x, layer1], dim=1)
        x = self.conv_up1(x)

        x = self.upsample(x)
        layer0 = self.layer0_1x1(layer0)
        x = torch.cat([x, layer0], dim=1)
        x = self.conv_up0(x)

        x = self.upsample(x)
        x = torch.cat([x, x_original], dim=1)
        x = self.conv_original_size2(x)

        out = self.conv_last(x)

        return out

In [31]:
model = ResNetUNet()

In [32]:
learning_rate = 0.001
num_epochs = 5 

# Criterion and Optimizer
criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [33]:
for epoch in range(num_epochs): 
    for i, (inputs, targets) in enumerate(all_loader):
        model.train()
        optimizer.zero_grad()
        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        #print(loss)
        # Backward and optimize
        loss.backward()
        optimizer.step()
        # validate every 10 iterations
        if i > 0 and i % 100 == 0:
            # validate
            val_acc = test_model(val_loader, model)
            #train_acc = test_model(train_loader, model)
            print("Training Loss : {}".format(loss))
            #print("Training Accuracy : {}".format(train_acc))
            print('Epoch: [{}/{}], Step: [{}/{}], Validation Acc: {}'.format(
                       epoch+1, num_epochs, i+1, len(train_loader), val_acc))

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 3, 3], but got input of size [4, 512, 512] instead